Fixed Build Failed - gcc 8.2.0
ERROR:

main.cpp:2841:10: error: ‘char* strncpy(char*, const char*, size_t)’
output truncated before terminating nul copying as many bytes from
a string as its length [-Werror=stringop-truncation]

Since the allocation is only 100*char, the reasonable fix would be
limit the strncpy to only (100-1)*char.